"use client";

import * as React from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Modal, ModalContent, ModalHeader, ModalTitle, ModalDescription, ModalTrigger, ModalClose } from "@/components/ui/modal";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { EmptyState } from "@/components/ui/empty-state";
import { useToast } from "@/components/ui/toaster";
import { MermaidViewer } from "@/components/mindmaps/mermaid-viewer";
import { Plus, GitFork, Loader2, Trash2, Search, Network, Share2, PieChart as PieChartIcon } from "lucide-react";
import type { MindMap, NoteSection, DiagramType } from "@/lib/types";
import { formatShortDate } from "@/lib/utils";

interface Props {
  initialMindMaps: MindMap[];
}

const diagramTypeLabels: Record<DiagramType, { label: string; icon: React.ReactNode }> = {
  mindmap: { label: "Mind Map", icon: <GitFork className="h-3.5 w-3.5" /> },
  graph: { label: "Flowchart / Graph", icon: <Network className="h-3.5 w-3.5" /> },
  sequence: { label: "Sequence Flow", icon: <Share2 className="h-3.5 w-3.5" /> },
  pie: { label: "Pie Chart", icon: <PieChartIcon className="h-3.5 w-3.5" /> },
};

/**
 * MindMapsClient — Visual diagram generator & viewer powered by OmniRoute.
 */
export function MindMapsClient({ initialMindMaps }: Props) {
  const qc = useQueryClient();
  const { toast } = useToast();
  const [open, setOpen] = React.useState(false);
  const [topic, setTopic] = React.useState("");
  const [section, setSection] = React.useState<NoteSection>("QA");
  const [diagramType, setDiagramType] = React.useState<DiagramType>("mindmap");
  const [activeSection, setActiveSection] = React.useState<"ALL" | NoteSection>("ALL");
  const [searchQuery, setSearchQuery] = React.useState("");

  const { data: mindmaps = initialMindMaps, isLoading } = useQuery({
    queryKey: ["mindmaps"],
    queryFn: async () => {
      const res = await fetch("/api/mindmaps");
      if (!res.ok) throw new Error("Failed to load mindmaps");
      const json = await res.json();
      return json.data as MindMap[];
    },
    initialData: initialMindMaps,
  });

  const generateMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch("/api/mindmaps/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topic, section, diagramType }),
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error?.message ?? "Generation failed");
      }
      return res.json();
    },
    onSuccess: (res) => {
      if (res?.data) {
        qc.setQueryData(["mindmaps"], (old: MindMap[] | undefined) => [
          res.data,
          ...(old ?? []),
        ]);
      }
      setOpen(false);
      setTopic("");
      toast({ title: "Diagram generated via OmniRoute", tone: "success" });
    },
    onError: (err: Error) => {
      toast({ title: "Generation failed", description: err.message, tone: "error" });
    },
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      const res = await fetch(`/api/mindmaps/${id}`, { method: "DELETE" });
      if (!res.ok) throw new Error("Failed to delete diagram");
      return id;
    },
    onSuccess: (id) => {
      qc.setQueryData(["mindmaps"], (old: MindMap[] | undefined) =>
        old ? old.filter((m) => m.id !== id) : []
      );
      toast({ title: "Diagram deleted", tone: "success" });
    },
  });

  const filteredMindMaps = React.useMemo(() => {
    return mindmaps.filter((m) => {
      const matchesSec = activeSection === "ALL" || m.section === activeSection;
      const matchesSearch =
        !searchQuery.trim() ||
        m.topic.toLowerCase().includes(searchQuery.toLowerCase());
      return matchesSec && matchesSearch;
    });
  }, [mindmaps, activeSection, searchQuery]);

  return (
    <div className="space-y-6">
      <header className="flex items-center justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-heading-1 text-ink tracking-tight">Mind Maps & Visual Graphs</h1>
          <p className="text-body-sm text-ink-muted mt-1">
            Visual concept maps, flowcharts, and decision graphs generated by OmniRoute.
          </p>
        </div>
        <Modal open={open} onOpenChange={setOpen}>
          <ModalTrigger asChild>
            <Button>
              <Plus className="h-4 w-4" /> Generate Diagram
            </Button>
          </ModalTrigger>
          <ModalContent className="w-full max-w-lg sm:max-w-xl">
            <ModalHeader>
              <ModalTitle>Generate Visual Diagram via OmniRoute</ModalTitle>
              <ModalDescription>
                Creates interactive Mermaid.js mind maps, decision flowcharts, and topic breakdowns.
              </ModalDescription>
            </ModalHeader>
            <div className="space-y-4">
              <div className="space-y-1.5">
                <Label htmlFor="diagram-topic">Topic Title</Label>
                <Input
                  id="diagram-topic"
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  placeholder="e.g. Geometry formula web & properties"
                  autoFocus
                />
              </div>

              <div className="space-y-1.5">
                <Label>Diagram Format</Label>
                <div className="grid grid-cols-2 gap-2">
                  {(Object.keys(diagramTypeLabels) as DiagramType[]).map((type) => {
                    const item = diagramTypeLabels[type];
                    const isSelected = diagramType === type;
                    return (
                      <button
                        key={type}
                        type="button"
                        onClick={() => setDiagramType(type)}
                        className={`p-2.5 rounded-lg border text-left text-body-sm transition-all flex items-center gap-2 ${
                          isSelected
                            ? "border-[var(--color-primary)] bg-[rgba(0,117,222,0.06)] text-[var(--color-primary)] font-semibold"
                            : "border-hairline hover:border-ink-muted text-ink-muted"
                        }`}
                      >
                        {item.icon}
                        <span>{item.label}</span>
                      </button>
                    );
                  })}
                </div>
              </div>

              <div className="space-y-1.5">
                <Label>Section</Label>
                <div className="flex gap-2">
                  {(["QA", "DILR", "VARC"] as NoteSection[]).map((s) => (
                    <Button
                      key={s}
                      type="button"
                      variant={section === s ? "primary" : "utility"}
                      onClick={() => setSection(s)}
                      size="sm"
                    >
                      {s}
                    </Button>
                  ))}
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-2">
                <ModalClose asChild>
                  <Button variant="utility">Cancel</Button>
                </ModalClose>
                <Button
                  onClick={() => generateMutation.mutate()}
                  disabled={!topic.trim() || generateMutation.isPending}
                >
                  {generateMutation.isPending ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" /> Generating Diagram…
                    </>
                  ) : (
                    "Generate Diagram"
                  )}
                </Button>
              </div>
            </div>
          </ModalContent>
        </Modal>
      </header>

      {/* Filter Tabs & Search */}
      <div className="flex items-center justify-between gap-4 flex-wrap pb-2 border-b border-hairline">
        <div className="flex items-center gap-1.5 flex-wrap">
          {(["ALL", "QA", "DILR", "VARC"] as const).map((sec) => (
            <button
              key={sec}
              type="button"
              onClick={() => setActiveSection(sec)}
              className={`px-3 py-1.5 rounded-lg text-body-sm font-medium transition-all ${
                activeSection === sec
                  ? "bg-[var(--color-primary)] text-white shadow-xs"
                  : "bg-black/5 text-ink-muted hover:text-ink hover:bg-black/10"
              }`}
            >
              {sec === "ALL" ? "All Diagrams" : sec}
            </button>
          ))}
        </div>

        <div className="relative flex-1 min-w-0 w-full sm:w-auto sm:min-w-[200px]">
          <Search className="h-3.5 w-3.5 absolute left-3 top-1/2 -translate-y-1/2 text-ink-faint" />
          <Input
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search diagrams..."
            className="pl-8 text-body-sm h-8 w-full"
          />
        </div>
      </div>

      {isLoading ? (
        <div className="space-y-4">
          <Skeleton className="h-64 w-full" />
          <Skeleton className="h-64 w-full" />
        </div>
      ) : filteredMindMaps.length === 0 ? (
        <EmptyState
          icon={<GitFork className="h-8 w-8" />}
          title={searchQuery ? "No matching diagrams" : "No diagrams generated yet"}
          description="Generate visual mind maps, decision flowcharts, and concept trees via OmniRoute."
          action={
            <Button onClick={() => setOpen(true)}>
              <Plus className="h-4 w-4" /> Generate Diagram
            </Button>
          }
        />
      ) : (
        <div className="space-y-6">
          {filteredMindMaps.map((m) => (
            <div key={m.id} className="space-y-2">
              <div className="flex items-center justify-between gap-2 flex-wrap px-1">
                <div className="flex items-center gap-2">
                  <Badge tone={m.section === "QA" ? "qa" : m.section === "DILR" ? "dilr" : "varc"}>
                    {m.section}
                  </Badge>
                  <span className="text-caption font-medium text-ink-secondary flex items-center gap-1">
                    {diagramTypeLabels[m.diagramType]?.icon}
                    {diagramTypeLabels[m.diagramType]?.label ?? m.diagramType}
                  </span>
                  <span className="text-caption text-ink-faint">
                    · {formatShortDate(m.createdAt)}
                  </span>
                </div>
                <button
                  type="button"
                  onClick={() => {
                    if (confirm(`Delete diagram "${m.topic}"?`)) {
                      deleteMutation.mutate(m.id);
                    }
                  }}
                  title="Delete diagram"
                  className="p-1 rounded-md text-ink-faint hover:text-accent-orange-deep hover:bg-black/5 transition-colors"
                >
                  <Trash2 className="h-4 w-4" />
                </button>
              </div>
              <MermaidViewer chart={m.mermaidCode} topic={m.topic} />
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
